<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function countArticleComments($articleId){
        $q = $this->_em->createQueryBuilder()
            ->select('count(comment)')
            ->from('AppBundle:Comment', 'comment')
            ->where("comment.post = $articleId");

        $count = $q->getQuery()->getSingleScalarResult();

        return $count;
    }

    public function getArticleComments($articleId){
        return $this->findBy(array('post' => $articleId));

    }
}
